# Base blog settings
baseurl                      : "/Remember" # the subpath of your site,                         # e.g. /blog/
                              # set to '' in case of hosting on GitHub
# url                          : "http://funzmr.github.io" # the base hostname & protocol for your site
#                                   # `http://<username>.github.io` - for GitHub
url							 : "http://freefun.fun"
root						 : "/"

blog:
  title                      : FUN
  description                  : >
                               We're

# Layout configuration
  logo_path                  : #"assets/img/dactl.svg" # path to logo fileUS
  # search_path                : "funzmr.github.io"
  search_path                : "http://freefun.fun"
                               # needed for searchbox in archive page
  hero_layout                : true # turn on hero layout for blog and posts
  hero_placeholder           : "assets/img/generic_hero.jpg" # placeholder for hero image
  excerpts                   : true # show excerpts instead of full post content on blog page
  inline_footnotes           : true # enable/disable barefoot inline footnotes
  titles_only                : false # show post titles only on main blog page

# Fonts
  font                       : '"Rubik", -apple-system, BlinkMacSystemFont, "Helvetica Neue", sans-serif'
  load_google_fonts          : 'Rubik:400,400italic,700,700italic'


# Author info
author:
  fullname                  : FUN
  # rss                       : true # generate RSS feed and show it's icon in header
  # mail                      : your@email.com # change to your e-mail address
  # twitter                   : true # twitter-user-name————————————
  # github                    : "FUNzmr" # github-user-name
  # youtube                   : true # youtube-user-name————————————
  # stackoverflow             : true # stackoverflow-user-name——————————
  disqus                    : true # dactl # your disqus site name
  google_analytics          : # 'UA-XXXXXXXX-X'
  photo                     : "uploads/youandme.png"
  photo2x                   : "uploads/youandme.png"

# Valine评论系统开关
# You can get your appid and appkey from https://leancloud.app
# more info please open https://valine.js.org
valine:
  enable: true
  appid:  Ey1ea9rKccS26vqCqvauaXuI-MdYXbMMI # your leancloud app id
  appkey: u6vG3pP3jdraMeUUHIwheV5u # your leancloud app key
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 来都来了，不说点啥？ # comment box placeholder
  avatar:   # gravatar style
  guest_info: 昵称,邮箱,网址 # custom comment header
  pageSize: 9 # pagination size
  # path: window.location.pathname


## !!
## Advanced blog settings
## You should not change anything here unless you know what you are doing

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Permalinks
permalink                    : posts/:slug

# Posts
excerpt_separator            : <!–-break-–>

# Pagination
paginate                     : 3
paginate_path                : '/page-:num/'

# Tags
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog-by-tag

# Handling Reading
exclude                    : ["README.md", "README.html"]

# https://github.com/jekyll/jekyll/issues/4619
# Markdown and highlighter settings
markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sass settings
sass:
  sass_dir                : _sass
  style                   : compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings               : all
  endings                 : all
  comments                : ["<!-- ", " -->"]
  blanklines              : true
  profile                 : false
  ignore:
  envs                    : [local]
